name: Publish NuGet Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Verify API key
        run: |
          if [ -z "${{ secrets.NUGET_API_KEY }}" ]; then
            echo "Missing NUGET_API_KEY secret"
            exit 1
          fi

      - run: dotnet restore src/Serilog.Sinks.Email/Serilog.Sinks.Email.csproj
      - run: dotnet build --configuration Release --no-restore src/Serilog.Sinks.Email/Serilog.Sinks.Email.csproj
      - run: dotnet pack --configuration Release --no-build --output ./nupkg src/Serilog.Sinks.Email/Serilog.Sinks.Email.csproj
      - name: Push
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
